[project]
name = "pyladies-kurz"
version = "2024.9.1"
description = "Kurz pro PyLadies"
authors = [
    {name = "Jan Pipek", email = "jan.pipek@gmail.com"},
    {name = "Jakub Urban", email = "coobas@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    "jupyter-book==2.1.6",
]

[tool.uv.workspace]
members = ["lessons"]
